import 'package:flutter/widgets.dart';

/// Hand-written localisation (no code generation). The parent area uses the language chosen in settings
/// (Arabic by default, RTL); the child area always uses English. A test keeps both maps in sync.
class Strings {
  const Strings._(this._m, this.locale);

  final Map<String, String> _m;
  final Locale locale;

  static const ar = Strings._(_arabic, Locale('ar'));
  static const en = Strings._(_english, Locale('en'));

  static Strings forCode(String code) => code == 'en' ? en : ar;

  bool get isRtl => locale.languageCode == 'ar';
  TextDirection get direction => isRtl ? TextDirection.rtl : TextDirection.ltr;

  /// `s('save')`. A missing key is a bug caught by the parity test; at runtime the key itself is shown.
  String call(String key) => _m[key] ?? key;

  /// A number in the digits of the language (Arabic-Indic for Arabic).
  String number(int n) => isRtl ? n.toString().split('').map((c) => c == '-' ? c : String.fromCharCode(0x0660 + int.parse(c))).join() : '$n';

  /// `format('pGreeting', {'name': 'Sara'})`: fills the {tokens} of a string; whole numbers use the language's digits.
  String format(String key, Map<String, Object> args) {
    var out = call(key);
    args.forEach((k, v) => out = out.replaceAll('{$k}', v is int ? number(v) : '$v'));
    return out;
  }

  /// "4 years" / "٤ سنوات" (with the Arabic singular and dual).
  String age(int years) => format(years == 1 ? 'ageOne' : years == 2 ? 'ageTwo' : (years <= 10 ? 'ageFew' : 'ageMany'), {'n': years});

  static Iterable<String> get arabicKeys => _arabic.keys;
  static Iterable<String> get englishKeys => _english.keys;
}

const Map<String, String> _arabic = {
  'appName': 'دندونة إنجليش',
  'welcomeTitle': 'أهلاً بك!',
  'welcomeBody': 'لنُنشئ ملفًا لطفلك ليبدأ تعلّم الإنجليزية بالأصوات والصور والمرح.',
  'start': 'ابدأ',
  'childProfiles': 'ملفات الأطفال',
  'addChild': 'إضافة طفل',
  'editChild': 'تعديل الملف',
  'childName': 'اسم الطفل (اسم مستعار)',
  'nameHint': 'من فضلك لا تُدخل الاسم الكامل',
  'birthYear': 'سنة الميلاد',
  'chooseAvatar': 'اختر صورة',
  'save': 'حفظ',
  'cancel': 'إلغاء',
  'delete': 'حذف',
  'deleteChildTitle': 'حذف الملف؟',
  'deleteChildBody': 'سيتم حذف الملف وتقدّم الطفل من هذا الجهاز، ومن حسابك على الخادم أيضًا إن كانت المزامنة مفعّلة.',
  'pendingDeletes': 'عمليات حذف بانتظار الاتصال بالخادم:',
  'errName': 'أدخل اسمًا من حرف إلى 30 حرفًا',
  'errBirthYear': 'سنة الميلاد غير مناسبة (العمر من 2 إلى 13 سنة)',
  'parentArea': 'منطقة الأهل',
  'dashboard': 'لوحة التقدّم',
  'noChildren': 'لا توجد ملفات بعد.',
  'stars': 'النجوم',
  'lettersDone': 'الدروس المكتملة',
  'settings': 'الإعدادات',
  'language': 'اللغة',
  'arabic': 'العربية',
  'english': 'English',
  'sessionLimit': 'مدة الجلسة بالدقائق',
  'unlockAll': 'فتح جميع الدروس',
  'unlockAllHint': 'للأهل أو للتجربة',
  'cardsTitle': 'بطاقات للبيت للطباعة',
  'cardsHint': 'صفحة لكل وحدة بكلماتها وأشياء بسيطة تفعلونها معًا. افتحوا هذا الرابط على أي جهاز واطبعوا ما تريدون. لا تتبّع ولا حساب.',
  'cardsCopy': 'نسخ الرابط',
  'cardsCopied': 'تم نسخ الرابط',
  'openChildMode': 'وضع الطفل',
  'gateTitle': 'للكبار فقط',
  'gateHold': 'اضغط مطوّلًا على الزر',
  'gateHoldButton': 'اضغط مطوّلًا',
  'gateSolve': 'احسب الناتج للمتابعة',
  'gateWrong': 'إجابة غير صحيحة، حاول مرة أخرى',
  'back': 'رجوع',
  'timeUpTitle': 'حان وقت الاستراحة',
  'timeUpBody': 'انتهى وقت اللعب. يمكن للكبار المتابعة.',
  'continue': 'متابعة',
  'loadError': 'تعذّر تحميل الدروس',
  'retry': 'إعادة المحاولة',
  'hi': 'أهلاً',
  'mapSoon': 'قريباً',
  'mapAlmostReady': 'تقريباً جاهز!',
  'pPackNeedsInternet': 'تحتاج إنترنت لتنزيلها',
  'pPackDownloading': 'جارٍ التنزيل…',
  'mapComingSoon': 'قريباً!',
  'mapFinishFirst': 'أكمل {unit} أولاً!',
  'mapPuzzleFirst': 'العب لعبة المراجعة أولاً!',
  'mapCastle': 'القلعة',
  'mapStory': 'قصة',
  'mapReview': 'مراجعة',
  'mapChest': 'كنز',
  'chestGotIt': 'حصلت عليه!',
  'chestNewOutfit': 'ملابس جديدة لدندونة!',
  'chestNewStickers': 'ملصقات جديدة!',
  'chestInside': 'ما كان في الصندوق',
  'chestTapOpen': 'اضغط لفتح الصندوق!',
  'stickerBook': 'كتاب الملصقات',
  'stickerBookCount': '{n} من {total}',
  'mapStickers': 'كتاب الملصقات',
  'reviewTitle': 'وقت المراجعة!',
  'reviewPassed': 'أحسنت! نجحت في المراجعة!',
  'reviewNotReady': 'لنتعلم المزيد من الكلمات أولاً!',
  'storyTheEnd': 'انتهت القصة!',
  'letterCapital': 'كبير',
  'letterSmall': 'صغير',
  'bin_head': 'الرأس',
  'bin_limbs': 'اليدان والقدمان',
  'bin_fruit': 'فاكهة',
  'bin_drink': 'مشروبات',
  'bin_treat': 'حلويات',
  'bin_warm': 'مشمس',
  'bin_cold': 'بارد',
  'bin_road': 'طريق',
  'bin_water': 'ماء',
  'bin_sky': 'سماء',
  'bin_bedroom': 'غرفة النوم',
  'bin_kitchen': 'المطبخ',
  'bin_living': 'غرفة المعيشة',
  'bin_grandparents': 'الجدّان',
  'bin_parents': 'الوالدان',
  'bin_children': 'الأطفال',
  'habitat_house': 'بيت',
  'habitat_farm': 'مزرعة',
  'habitat_water': 'ماء',
  'habitat_wild': 'برية',
  'mapParent': 'منطقة الأهل',
  'mapWhoIsPlaying': 'من يلعب؟',
  'certificate': 'شهادة',
  'certAwardedTo': 'مُنحت إلى',
  'certFinished': 'لإكمال وحدة',
  'hooray': 'مبروك!',
  // --- first-launch onboarding (parent area, Arabic) ---
  'obContinue': 'متابعة',
  'obBack': 'رجوع',
  'obWelcomeTitle': 'أهلاً بك في دندونة!',
  'obWelcomeBody': 'سنجهّز مساراً مناسباً لطفلك في دقيقتين.',
  'obNoAccount': 'ابدأ بدون حساب',
  'obAccount': 'إنشاء حساب / تسجيل الدخول',
  'obSignupTitle': 'أنشئ حسابك',
  'obLoginTitle': 'تسجيل الدخول',
  'obForgot': 'نسيت كلمة المرور؟',
  'obForgotTitle': 'استعادة كلمة المرور',
  'obForgotBody': 'اكتب بريدك وسنرسل لك رمزاً من 6 أرقام.',
  'obSendCode': 'أرسل الرمز',
  'obCodeTitle': 'اكتب الرمز وكلمة المرور الجديدة',
  'obCodeBody': 'إن كان لهذا البريد حساب فقد أرسلنا إليه رمزاً. صالح لدقائق قليلة.',
  'obCode': 'الرمز (6 أرقام)',
  'obNewPassword': 'كلمة المرور الجديدة',
  'obChangePassword': 'غيّر كلمة المرور',
  'obResend': 'أرسل الرمز مرة أخرى',
  'obPasswordChanged': 'تم تغيير كلمة المرور. سجّل الدخول بها.',
  'obCodeInvalid': 'الرمز غير صحيح أو انتهت صلاحيته، أو كلمة المرور أقصر من 8 أحرف.',
  'obEmail': 'البريد الإلكتروني',
  'obPassword': 'كلمة المرور',
  'obFirstName': 'الاسم الأول (اختياري)',
  'obGuardian': 'أنا والد الطفل أو وليّ أمره وعمري ١٨ سنة أو أكثر',
  'obAgreePre': 'أوافق على ',
  'obPrivacy': 'سياسة الخصوصية',
  'obAnd': ' و',
  'obTerms': 'الشروط',
  'obCreate': 'إنشاء الحساب',
  'obLogin': 'دخول',
  'obHaveAccount': 'لديّ حساب بالفعل',
  'obNoAccountYet': 'ليس لديّ حساب',
  'obNameTitle': 'ما اسم طفلك؟',
  'obNameHint': 'يكفي اسم مستعار، لا حاجة للاسم الكامل',
  'obNameLabel': 'اسم الطفل (اسم مستعار)',
  'obAvatarTitle': 'اختر صورة',
  'obAgeTitle': 'متى وُلد طفلك؟',
  'obMonth': 'الشهر',
  'obYear': 'السنة',
  'obTrackFor': 'المسار المناسب:',
  'obTrackLL': 'المتعلّمون الصغار (٣–٥ سنوات)',
  'obTrackSoon': 'دروس عمرك قادمة قريباً',
  'obTrackExplorers': 'المستكشفون (٦–٨ سنوات)',
  'obTrackTitle': 'أي مسار؟',
  'obTrackAuto': 'اخترناه حسب العمر، ويمكنك تغييره.',
  'obMonth1': 'يناير',
  'obMonth2': 'فبراير',
  'obMonth3': 'مارس',
  'obMonth4': 'أبريل',
  'obMonth5': 'مايو',
  'obMonth6': 'يونيو',
  'obMonth7': 'يوليو',
  'obMonth8': 'أغسطس',
  'obMonth9': 'سبتمبر',
  'obMonth10': 'أكتوبر',
  'obMonth11': 'نوفمبر',
  'obMonth12': 'ديسمبر',
  'obLevelTitle': 'كم يعرف طفلك من الإنجليزية؟',
  'obLevel0': 'لا يعرف أي إنجليزية بعد',
  'obLevel1': 'يعرف بعض الحروف',
  'obLevel2': 'يعرف كل الحروف',
  'obLevel3': 'يقرأ كلمات بسيطة',
  'obGoalTitle': 'كم دقيقة في اليوم؟',
  'obGoalHint': 'القليل كل يوم أفضل من الكثير نادراً',
  'obGoal5': '5 دقائق',
  'obGoal10': '10 دقائق',
  'obGoal15': '15 دقيقة',
  'obGoal5Sub': 'بداية خفيفة',
  'obGoal10Sub': 'الأنسب لمعظم الأطفال',
  'obGoal15Sub': 'لمن يحب التعلّم',
  'obRemindTitle': 'هل نذكّرك كل يوم؟',
  'obRemindBody': 'تذكير على هذا الهاتف فقط، بدون أي خدمة خارجية',
  'obTimeMorning': 'صباحاً 8:00',
  'obTimeAfternoon': 'عصراً 4:00',
  'obTimeEvening': 'مساءً 7:00',
  'obRemindMe': 'ذكّرني',
  'obRemindLater': 'ذكّرني لاحقاً',
  'obReminderTitle': 'حان وقت التعلّم مع دندونة!',
  'obReminderBody': 'بضع دقائق اليوم تصنع فرقاً.',
  'obReminderDenied': 'الإشعارات متوقفة على هذا الهاتف. يمكنك السماح بها من إعدادات الهاتف.',
  'obNoReminder': 'بدون تذكير',
  'obPathReady': 'مسار {name} جاهز!',
  'obRowTrack': 'المسار',
  'obRowStart': 'نقطة البداية',
  'obRowGoal': 'الهدف اليومي',
  'obRowReminder': 'التذكير',
  'obStartLearning': 'ابدأ التعلّم',
  'obGreetIam': 'أنا دندونة!',
  'obGreetLets': "Let's learn English together!",
  'obLetsGo': "Let's go!",
  'whoIsPlaying': 'من سيلعب؟',
  'wardrobeHint': 'اجمع النجوم لفتح إكسسوارات جديدة',
  'thisWeek': 'هذا الأسبوع',
  // --- parent area redesign ---
  'ageOne': 'سنة واحدة',
  'ageTwo': 'سنتان',
  'ageFew': '{n} سنوات',
  'ageMany': '{n} سنة',
  'pGreeting': 'أهلاً، {name}',
  'pNowLearning': 'يتعلّم الآن: {unit}',
  'pUnitLessons': '{unit} · {done} من {total} دروس',
  'pUnitsDone': 'الوحدات المكتملة: {done} من {total}',
  'pNoActivity': 'لا نشاط هذا الأسبوع بعد. دندونة تنتظر!',
  'pManageChildren': 'إدارة الأطفال',
  'pManageHint': 'اضغط على طفل للتعديل أو الحذف',
  'pAddFirstChild': 'أضف طفلك الأول',
  'pEditChild': 'تعديل الطفل',
  'pNickname': 'الاسم المستعار',
  'pTrack': 'المسار',
  'pTrackLL': 'المتعلّمون الصغار (٣–٥ سنوات)',
  'pTrackExplorers': 'المستكشفون (٦–٨ سنوات)',
  'pStartUnit': 'نقطة البداية',
  'pAskMonth': 'أضف شهر ميلاد {name} لنختار له الدروس المناسبة لعمره بدقة.',
  'pAskMonthAdd': 'إضافة الشهر',
  'pNotNow': 'ليس الآن',
  'pExplorersOffer': '{name} جاهز لمسار المستكشفين (٦–٨ سنوات): قراءة وكتابة كلمات وجمل.',
  'pExplorersKeeps': 'تبقى الشهادات والصناديق وملابس دندونة. يمكنك التغيير لاحقاً من تعديل الطفل.',
  'pExplorersYes': 'جرّب المستكشفين',
  'pExplorersStay': 'البقاء',
  'pTrackChampions': 'الأبطال (٩ سنوات فأكثر)',
  'pSoon': 'قريباً',
  'pSuggested': 'مقترح حسب العمر',
  'pDailyGoal': 'الهدف اليومي',
  'pReminderTime': 'وقت التذكير',
  'pReminderOff': 'بدون',
  'pMinutesShort': '{n} د',
  'pDiscardTitle': 'تجاهل التغييرات؟',
  'pDiscardBody': 'لن تُحفظ التعديلات التي أجريتها.',
  'pDiscard': 'تجاهل',
  'pKeepEditing': 'متابعة التعديل',
  'pRerunSetup': 'إعادة إعداد المسار',
  'pDeleteChild': 'حذف الطفل',
  'pDeleteTitle': 'حذف {name}؟',
  'pDeleteBody': 'سيتم حذف كل تقدّم {name} ونجومه وشهاداته من هذا الجهاز ومن حسابك. لا يمكن التراجع عن ذلك.',
  // --- child detail ---
  'dHearWords': 'اسمع الكلمات',
  'dStop': 'إيقاف',
  'dPractice': 'تدريب في المنزل',
  'dNothingToPractice': 'أحسنت! لا شيء للتدريب الآن',
  'dAllUnits': 'كل الوحدات',
  'dDone': 'مكتمل',
  'dCurrent': 'قيد التعلّم',
  'dLocked': 'مغلق',
  'dCertificates': 'الشهادات',
  'dNoCerts': 'تظهر الشهادات هنا عند إكمال وحدة',
  'dHistory': 'السجل',
  'dLastWeek': 'الأسبوع الماضي',
  'dThisMonth': 'هذا الشهر',
  'dTotalMinutes': '{n} دقيقة',
  'dActiveDays': '{n} أيام نشاط',
  'dLessonsOf': '{done} من {total} دروس',
  'dStars': '{n} نجمة',
  'dPlay': 'استمع',
  'syncTitle': 'الحساب والمزامنة',
  'deleteAccount': 'حذف الحساب وبياناته',
  'deleteAccountTitle': 'حذف الحساب نهائيًا؟',
  'deleteAccountBody': 'سيتم حذف حسابك وجميع الأطفال والتقدّم من الخادم نهائيًا. تبقى البيانات على هذا الجهاز.',
  'accountDeleted': 'تم حذف الحساب',
  'syncOptional': 'اختياري: التطبيق يعمل كاملاً بدون إنترنت.',
  'serverUrl': 'عنوان الخادم',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'login': 'تسجيل الدخول',
  'register': 'إنشاء حساب',
  'signOut': 'تسجيل الخروج',
  'syncNow': 'مزامنة الآن',
  'signedInAs': 'مسجّل الدخول:',
  'lastSync': 'آخر مزامنة',
  'signedInOk': 'تم تسجيل الدخول',
  'syncDone': 'تمت المزامنة',
  'syncNetwork': 'تعذّر الاتصال بالخادم',
  'syncAuth': 'البريد أو كلمة المرور غير صحيحة',
  'syncInvalid': 'تحقق من البيانات المدخلة',
  'syncFailed': 'فشلت المزامنة، حاول لاحقًا',
  'activities': 'الأنشطة',
  'minutes': 'الدقائق',
  'activeDays': 'أيام النشاط',
  'd0': 'إث',
  'd1': 'ثل',
  'd2': 'أر',
  'd3': 'خم',
  'd4': 'جم',
  'd5': 'سب',
  'd6': 'أح',
};

const Map<String, String> _english = {
  'appName': 'Dandoona English',
  'welcomeTitle': 'Welcome!',
  'welcomeBody': "Let's create a profile for your child to start learning English with sounds, pictures and fun.",
  'start': 'Start',
  'childProfiles': 'Child profiles',
  'addChild': 'Add child',
  'editChild': 'Edit profile',
  'childName': "Child's nickname",
  'nameHint': "Please don't enter a full name",
  'birthYear': 'Birth year',
  'chooseAvatar': 'Choose an avatar',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'deleteChildTitle': 'Delete this profile?',
  'deleteChildBody': "The profile and progress will be removed from this device, and from your synced account on the server if sync is on.",
  'pendingDeletes': 'Deletions waiting to reach the server:',
  'errName': 'Enter a name (1-30 characters)',
  'errBirthYear': 'Birth year must give an age of 2 to 13',
  'parentArea': 'Parent area',
  'dashboard': 'Progress dashboard',
  'noChildren': 'No profiles yet.',
  'stars': 'Stars',
  'lettersDone': 'Lessons completed',
  'settings': 'Settings',
  'language': 'Language',
  'arabic': 'العربية',
  'english': 'English',
  'sessionLimit': 'Session length (minutes)',
  'unlockAll': 'Unlock all lessons',
  'unlockAllHint': 'For parents or testing',
  'cardsTitle': 'Printable cards for home',
  'cardsHint': 'One page for every unit with its words and easy things to do together. Open this link on any device and print what you like. No tracking, no account.',
  'cardsCopy': 'Copy link',
  'cardsCopied': 'Link copied',
  'openChildMode': 'Child mode',
  'gateTitle': 'Grown-ups only',
  'gateHold': 'Press and hold the button',
  'gateHoldButton': 'Hold',
  'gateSolve': 'Solve to continue',
  'gateWrong': 'Not quite, try again',
  'back': 'Back',
  'timeUpTitle': 'Time to rest',
  'timeUpBody': 'Play time is over. A grown-up can continue.',
  'continue': 'Continue',
  'loadError': "Couldn't load the lessons",
  'retry': 'Try again',
  'hi': 'Hi',
  'mapSoon': 'Soon',
  'mapAlmostReady': 'Almost ready!',
  'pPackNeedsInternet': 'Needs internet to download',
  'pPackDownloading': 'Downloading…',
  'mapComingSoon': 'Coming soon!',
  'mapFinishFirst': 'Finish {unit} first!',
  'mapPuzzleFirst': 'Play the puzzle first!',
  'mapCastle': 'Castle',
  'mapStory': 'Story',
  'mapReview': 'Review',
  'mapChest': 'Treasure',
  'chestGotIt': 'Got it!',
  'chestNewOutfit': 'A new outfit for Dandoona!',
  'chestNewStickers': 'New stickers!',
  'chestInside': 'Inside the chest',
  'chestTapOpen': 'Tap to open the chest!',
  'stickerBook': 'Sticker Book',
  'stickerBookCount': '{n} of {total}',
  'mapStickers': 'Sticker Book',
  'reviewTitle': 'Review time!',
  'reviewPassed': 'You passed the review!',
  'reviewNotReady': "Let's learn more words first!",
  'storyTheEnd': 'The end!',
  'letterCapital': 'Capital',
  'letterSmall': 'Small',
  'bin_head': 'Head',
  'bin_limbs': 'Arms and legs',
  'bin_fruit': 'Fruit',
  'bin_drink': 'Drinks',
  'bin_treat': 'Treats',
  'bin_warm': 'Sunny',
  'bin_cold': 'Cold',
  'bin_road': 'Road',
  'bin_water': 'Water',
  'bin_sky': 'Sky',
  'bin_bedroom': 'Bedroom',
  'bin_kitchen': 'Kitchen',
  'bin_living': 'Living room',
  'bin_grandparents': 'Grandparents',
  'bin_parents': 'Parents',
  'bin_children': 'Children',
  'habitat_house': 'House',
  'habitat_farm': 'Farm',
  'habitat_water': 'Water',
  'habitat_wild': 'Wild',
  'mapParent': 'Parent area',
  'mapWhoIsPlaying': 'Who is playing?',
  'certificate': 'Certificate',
  'certAwardedTo': 'Awarded to',
  'certFinished': 'for finishing',
  'hooray': 'Hooray!',
  // --- first-launch onboarding (parent area, English) ---
  'obContinue': 'Continue',
  'obBack': 'Back',
  'obWelcomeTitle': 'Welcome to Dandoona!',
  'obWelcomeBody': "We'll set up the right path for your child in two minutes.",
  'obNoAccount': 'Start without an account',
  'obAccount': 'Create account / Log in',
  'obSignupTitle': 'Create your account',
  'obLoginTitle': 'Log in',
  'obForgot': 'Forgot your password?',
  'obForgotTitle': 'Reset your password',
  'obForgotBody': "Type your email and we'll send you a 6-digit code.",
  'obSendCode': 'Send the code',
  'obCodeTitle': 'Type the code and a new password',
  'obCodeBody': 'If that email has an account we sent it a code. It works for a few minutes.',
  'obCode': 'Code (6 digits)',
  'obNewPassword': 'New password',
  'obChangePassword': 'Change password',
  'obResend': 'Send the code again',
  'obPasswordChanged': 'Password changed. Log in with it.',
  'obCodeInvalid': 'The code is wrong or has expired, or the password is shorter than 8 characters.',
  'obEmail': 'Email',
  'obPassword': 'Password',
  'obFirstName': 'First name (optional)',
  'obGuardian': "I am the child's parent or guardian and I'm 18 or older",
  'obAgreePre': 'I agree to the ',
  'obPrivacy': 'Privacy Policy',
  'obAnd': ' and ',
  'obTerms': 'Terms',
  'obCreate': 'Create account',
  'obLogin': 'Log in',
  'obHaveAccount': 'I already have an account',
  'obNoAccountYet': "I don't have an account",
  'obNameTitle': "What's your child's name?",
  'obNameHint': 'A nickname is enough, no full name needed',
  'obNameLabel': 'Nickname',
  'obAvatarTitle': 'Pick a picture',
  'obAgeTitle': 'When was your child born?',
  'obMonth': 'Month',
  'obYear': 'Year',
  'obTrackFor': 'Best track:',
  'obTrackLL': 'Little Learners (ages 3–5)',
  'obTrackSoon': 'lessons for this age are coming soon',
  'obTrackExplorers': 'Explorers (ages 6–8)',
  'obTrackTitle': 'Which track?',
  'obTrackAuto': 'We chose it from the age. You can change it.',
  'obMonth1': 'January',
  'obMonth2': 'February',
  'obMonth3': 'March',
  'obMonth4': 'April',
  'obMonth5': 'May',
  'obMonth6': 'June',
  'obMonth7': 'July',
  'obMonth8': 'August',
  'obMonth9': 'September',
  'obMonth10': 'October',
  'obMonth11': 'November',
  'obMonth12': 'December',
  'obLevelTitle': 'How much English does your child know?',
  'obLevel0': "Doesn't know any English yet",
  'obLevel1': 'Knows some letters',
  'obLevel2': 'Knows all letters',
  'obLevel3': 'Reads simple words',
  'obGoalTitle': 'How many minutes a day?',
  'obGoalHint': 'A little every day beats a lot once in a while',
  'obGoal5': '5 minutes',
  'obGoal10': '10 minutes',
  'obGoal15': '15 minutes',
  'obGoal5Sub': 'A light start',
  'obGoal10Sub': 'Best for most children',
  'obGoal15Sub': 'For keen learners',
  'obRemindTitle': 'Shall we remind you every day?',
  'obRemindBody': 'A reminder on this phone only, no outside service',
  'obTimeMorning': 'Morning 8:00',
  'obTimeAfternoon': 'Afternoon 4:00',
  'obTimeEvening': 'Evening 7:00',
  'obRemindMe': 'Remind me',
  'obRemindLater': 'Remind me later',
  'obReminderTitle': 'Time to learn with Dandoona!',
  'obReminderBody': 'A few minutes today make a difference.',
  'obReminderDenied': 'Notifications are off on this phone. You can allow them in the phone settings.',
  'obNoReminder': 'No reminder',
  'obPathReady': "{name}'s path is ready!",
  'obRowTrack': 'Track',
  'obRowStart': 'Starting point',
  'obRowGoal': 'Daily goal',
  'obRowReminder': 'Reminder',
  'obStartLearning': 'Start learning',
  'obGreetIam': "I'm Dandoona!",
  'obGreetLets': "Let's learn English together!",
  'obLetsGo': "Let's go!",
  'whoIsPlaying': 'Who is playing?',
  'wardrobeHint': 'Collect stars to unlock new accessories',
  'thisWeek': 'This week',
  // --- parent area redesign ---
  'ageOne': '1 year',
  'ageTwo': '2 years',
  'ageFew': '{n} years',
  'ageMany': '{n} years',
  'pGreeting': 'Hi, {name}',
  'pNowLearning': 'Now learning: {unit}',
  'pUnitLessons': '{unit} · {done} of {total} lessons',
  'pUnitsDone': 'Units completed: {done} of {total}',
  'pNoActivity': 'No activity this week yet. Dandoona is waiting!',
  'pManageChildren': 'Manage children',
  'pManageHint': 'Tap a child to edit or delete',
  'pAddFirstChild': 'Add your first child',
  'pEditChild': 'Edit child',
  'pNickname': 'Nickname',
  'pTrack': 'Track',
  'pTrackLL': 'Little Learners (ages 3–5)',
  'pTrackExplorers': 'Explorers (ages 6–8)',
  'pStartUnit': 'Starting point',
  'pAskMonth': "Add {name}'s birth month so the lessons fit their age exactly.",
  'pAskMonthAdd': 'Add the month',
  'pNotNow': 'Not now',
  'pExplorersOffer': '{name} is ready for Explorers (ages 6–8): reading and writing words and sentences.',
  'pExplorersKeeps': "Certificates, chests and Dandoona's outfits stay. You can change it later in Edit child.",
  'pExplorersYes': 'Try Explorers',
  'pExplorersStay': 'Stay',
  'pTrackChampions': 'Champions (ages 9 and up)',
  'pSoon': 'Soon',
  'pSuggested': 'Suggested for the age',
  'pDailyGoal': 'Daily goal',
  'pReminderTime': 'Reminder time',
  'pReminderOff': 'Off',
  'pMinutesShort': '{n} min',
  'pDiscardTitle': 'Discard changes?',
  'pDiscardBody': "The changes you made won't be saved.",
  'pDiscard': 'Discard',
  'pKeepEditing': 'Keep editing',
  'pRerunSetup': 'Run the setup again',
  'pDeleteChild': 'Delete child',
  'pDeleteTitle': 'Delete {name}?',
  'pDeleteBody': "All of {name}'s progress, stars and certificates will be deleted from this device and from your account. This can't be undone.",
  // --- child detail ---
  'dHearWords': 'Hear the words',
  'dStop': 'Stop',
  'dPractice': 'Practice at home',
  'dNothingToPractice': 'Great job, nothing to practice right now',
  'dAllUnits': 'All units',
  'dDone': 'Done',
  'dCurrent': 'Learning now',
  'dLocked': 'Locked',
  'dCertificates': 'Certificates',
  'dNoCerts': 'Certificates appear here when a unit is finished',
  'dHistory': 'History',
  'dLastWeek': 'Last week',
  'dThisMonth': 'This month',
  'dTotalMinutes': '{n} minutes',
  'dActiveDays': '{n} active days',
  'dLessonsOf': '{done} of {total} lessons',
  'dStars': '{n} stars',
  'dPlay': 'Listen',
  'syncTitle': 'Account & sync',
  'deleteAccount': 'Delete account & data',
  'deleteAccountTitle': 'Delete the account permanently?',
  'deleteAccountBody': 'Your account, children and progress will be erased from the server for good. Data on this device stays.',
  'accountDeleted': 'Account deleted',
  'syncOptional': 'Optional: the app works fully offline.',
  'serverUrl': 'Server address',
  'email': 'Email',
  'password': 'Password',
  'login': 'Sign in',
  'register': 'Create account',
  'signOut': 'Sign out',
  'syncNow': 'Sync now',
  'signedInAs': 'Signed in as',
  'lastSync': 'Last sync',
  'signedInOk': 'Signed in',
  'syncDone': 'Synced',
  'syncNetwork': 'Could not reach the server',
  'syncAuth': 'Wrong email or password',
  'syncInvalid': 'Please check the details',
  'syncFailed': 'Sync failed, try again later',
  'activities': 'Activities',
  'minutes': 'Minutes',
  'activeDays': 'Active days',
  'd0': 'Mon',
  'd1': 'Tue',
  'd2': 'Wed',
  'd3': 'Thu',
  'd4': 'Fri',
  'd5': 'Sat',
  'd6': 'Sun',
};
