import 'package:flutter/widgets.dart';

/// Hand-written localisation (no code generation). The parent area uses the language chosen in settings
/// (Arabic by default, RTL); the child area always uses English. A test keeps both maps in sync.
class Strings {
  const Strings._(this._m, this.locale);

  final Map<String, String> _m;
  final Locale locale;

  static const ar = Strings._(_arabic, Locale('ar'));
  static const en = Strings._(_english, Locale('en'));

  static Strings forCode(String code) => code == 'en' ? en : ar;

  bool get isRtl => locale.languageCode == 'ar';
  TextDirection get direction => isRtl ? TextDirection.rtl : TextDirection.ltr;

  /// `s('save')`. A missing key is a bug caught by the parity test; at runtime the key itself is shown.
  String call(String key) => _m[key] ?? key;

  static Iterable<String> get arabicKeys => _arabic.keys;
  static Iterable<String> get englishKeys => _english.keys;
}

const Map<String, String> _arabic = {
  'appName': 'دندونة إنجليش',
  'welcomeTitle': 'أهلاً بك!',
  'welcomeBody': 'لنُنشئ ملفًا لطفلك ليبدأ تعلّم الإنجليزية بالأصوات والصور والمرح.',
  'start': 'ابدأ',
  'childProfiles': 'ملفات الأطفال',
  'addChild': 'إضافة طفل',
  'editChild': 'تعديل الملف',
  'childName': 'اسم الطفل (اسم مستعار)',
  'nameHint': 'من فضلك لا تُدخل الاسم الكامل',
  'birthYear': 'سنة الميلاد',
  'chooseAvatar': 'اختر صورة',
  'save': 'حفظ',
  'cancel': 'إلغاء',
  'delete': 'حذف',
  'deleteChildTitle': 'حذف الملف؟',
  'deleteChildBody': 'سيتم حذف الملف وتقدّم الطفل من هذا الجهاز، ومن حسابك على الخادم أيضًا إن كانت المزامنة مفعّلة.',
  'pendingDeletes': 'عمليات حذف بانتظار الاتصال بالخادم:',
  'errName': 'أدخل اسمًا من حرف إلى 30 حرفًا',
  'errBirthYear': 'سنة الميلاد غير مناسبة (العمر من 2 إلى 13 سنة)',
  'parentArea': 'منطقة الأهل',
  'dashboard': 'لوحة التقدّم',
  'noChildren': 'لا توجد ملفات بعد.',
  'stars': 'النجوم',
  'lettersDone': 'الدروس المكتملة',
  'settings': 'الإعدادات',
  'language': 'اللغة',
  'arabic': 'العربية',
  'english': 'English',
  'sessionLimit': 'مدة الجلسة بالدقائق',
  'unlockAll': 'فتح جميع الدروس',
  'unlockAllHint': 'للأهل أو للتجربة',
  'openChildMode': 'وضع الطفل',
  'gateTitle': 'للكبار فقط',
  'gateHold': 'اضغط مطوّلًا على الزر',
  'gateHoldButton': 'اضغط مطوّلًا',
  'gateSolve': 'احسب الناتج للمتابعة',
  'gateWrong': 'إجابة غير صحيحة، حاول مرة أخرى',
  'back': 'رجوع',
  'timeUpTitle': 'حان وقت الاستراحة',
  'timeUpBody': 'انتهى وقت اللعب. يمكن للكبار المتابعة.',
  'continue': 'متابعة',
  'loadError': 'تعذّر تحميل الدروس',
  'retry': 'إعادة المحاولة',
  'hi': 'أهلاً',
  'certificate': 'شهادة',
  'certAwardedTo': 'مُنحت إلى',
  'certFinished': 'لإكمال وحدة',
  'hooray': 'مبروك!',
  // --- first-launch onboarding (parent area, Arabic) ---
  'obContinue': 'متابعة',
  'obBack': 'رجوع',
  'obWelcomeTitle': 'أهلاً بك في دندونة إنجليش!',
  'obWelcomeBody': 'سنجهّز مساراً مناسباً لطفلك في دقيقتين.',
  'obNoAccount': 'ابدأ بدون حساب',
  'obNoAccountSub': 'كل شيء يبقى على هذا الجهاز',
  'obAccount': 'إنشاء حساب / تسجيل الدخول',
  'obAccountSub': 'للمزامنة بين الأجهزة وحفظ التقدّم',
  'obSignupTitle': 'أنشئ حسابك',
  'obLoginTitle': 'تسجيل الدخول',
  'obEmail': 'البريد الإلكتروني',
  'obPassword': 'كلمة المرور',
  'obFirstName': 'الاسم الأول (اختياري)',
  'obGuardian': 'أنا والد الطفل أو وليّ أمره وعمري ١٨ سنة أو أكثر',
  'obAgreePre': 'أوافق على ',
  'obPrivacy': 'سياسة الخصوصية',
  'obAnd': ' و',
  'obTerms': 'الشروط',
  'obCreate': 'إنشاء الحساب',
  'obLogin': 'دخول',
  'obHaveAccount': 'لديّ حساب بالفعل',
  'obNoAccountYet': 'ليس لديّ حساب',
  'obNameTitle': 'ما اسم طفلك؟',
  'obNameHint': 'يكفي اسم مستعار، لا حاجة للاسم الكامل',
  'obNameLabel': 'اسم الطفل (اسم مستعار)',
  'obAvatarTitle': 'اختر صورة',
  'obAgeTitle': 'متى وُلد طفلك؟',
  'obMonth': 'الشهر',
  'obYear': 'السنة',
  'obTrackFor': 'المسار المناسب:',
  'obTrackLL': 'المتعلّمون الصغار (٣–٥ سنوات)',
  'obMonth1': 'يناير',
  'obMonth2': 'فبراير',
  'obMonth3': 'مارس',
  'obMonth4': 'أبريل',
  'obMonth5': 'مايو',
  'obMonth6': 'يونيو',
  'obMonth7': 'يوليو',
  'obMonth8': 'أغسطس',
  'obMonth9': 'سبتمبر',
  'obMonth10': 'أكتوبر',
  'obMonth11': 'نوفمبر',
  'obMonth12': 'ديسمبر',
  'obLevelTitle': 'كم يعرف طفلك من الإنجليزية؟',
  'obLevel0': 'لا يعرف أي إنجليزية بعد',
  'obLevel1': 'يعرف بعض الحروف',
  'obLevel2': 'يعرف كل الحروف',
  'obLevel3': 'يقرأ كلمات بسيطة',
  'obGoalTitle': 'كم دقيقة في اليوم؟',
  'obGoalHint': 'القليل كل يوم أفضل من الكثير نادراً',
  'obGoal5': '5 دقائق',
  'obGoal10': '10 دقائق',
  'obGoal15': '15 دقيقة',
  'obGoal5Sub': 'بداية خفيفة',
  'obGoal10Sub': 'الأنسب لمعظم الأطفال',
  'obGoal15Sub': 'لمن يحب التعلّم',
  'obRemindTitle': 'هل نذكّرك كل يوم؟',
  'obRemindBody': 'تذكير على هذا الهاتف فقط، بدون أي خدمة خارجية',
  'obTimeMorning': 'صباحاً 8:00',
  'obTimeAfternoon': 'عصراً 4:00',
  'obTimeEvening': 'مساءً 7:00',
  'obRemindMe': 'ذكّرني',
  'obRemindLater': 'ذكّرني لاحقاً',
  'obNoReminder': 'بدون تذكير',
  'obPathReady': 'مسار {name} جاهز!',
  'obRowTrack': 'المسار',
  'obRowStart': 'نقطة البداية',
  'obRowGoal': 'الهدف اليومي',
  'obRowReminder': 'التذكير',
  'obStartLearning': 'ابدأ التعلّم',
  'obGreetIam': 'أنا دندونة!',
  'obGreetLets': "Let's learn English together!",
  'obLetsGo': "Let's go!",
  'whoIsPlaying': 'من سيلعب؟',
  'wardrobeHint': 'اجمع النجوم لفتح إكسسوارات جديدة',
  'thisWeek': 'هذا الأسبوع',
  'syncTitle': 'الحساب والمزامنة',
  'deleteAccount': 'حذف الحساب وبياناته',
  'deleteAccountTitle': 'حذف الحساب نهائيًا؟',
  'deleteAccountBody': 'سيتم حذف حسابك وجميع الأطفال والتقدّم من الخادم نهائيًا. تبقى البيانات على هذا الجهاز.',
  'accountDeleted': 'تم حذف الحساب',
  'syncOptional': 'اختياري: التطبيق يعمل كاملاً بدون إنترنت.',
  'serverUrl': 'عنوان الخادم',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'login': 'تسجيل الدخول',
  'register': 'إنشاء حساب',
  'signOut': 'تسجيل الخروج',
  'syncNow': 'مزامنة الآن',
  'signedInAs': 'مسجّل الدخول:',
  'lastSync': 'آخر مزامنة',
  'signedInOk': 'تم تسجيل الدخول',
  'syncDone': 'تمت المزامنة',
  'syncNetwork': 'تعذّر الاتصال بالخادم',
  'syncAuth': 'البريد أو كلمة المرور غير صحيحة',
  'syncInvalid': 'تحقق من البيانات المدخلة',
  'syncFailed': 'فشلت المزامنة، حاول لاحقًا',
  'activities': 'الأنشطة',
  'minutes': 'الدقائق',
  'activeDays': 'أيام النشاط',
  'd0': 'إث',
  'd1': 'ثل',
  'd2': 'أر',
  'd3': 'خم',
  'd4': 'جم',
  'd5': 'سب',
  'd6': 'أح',
};

const Map<String, String> _english = {
  'appName': 'Dandoona English',
  'welcomeTitle': 'Welcome!',
  'welcomeBody': "Let's create a profile for your child to start learning English with sounds, pictures and fun.",
  'start': 'Start',
  'childProfiles': 'Child profiles',
  'addChild': 'Add child',
  'editChild': 'Edit profile',
  'childName': "Child's nickname",
  'nameHint': "Please don't enter a full name",
  'birthYear': 'Birth year',
  'chooseAvatar': 'Choose an avatar',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'deleteChildTitle': 'Delete this profile?',
  'deleteChildBody': "The profile and progress will be removed from this device, and from your synced account on the server if sync is on.",
  'pendingDeletes': 'Deletions waiting to reach the server:',
  'errName': 'Enter a name (1-30 characters)',
  'errBirthYear': 'Birth year must give an age of 2 to 13',
  'parentArea': 'Parent area',
  'dashboard': 'Progress dashboard',
  'noChildren': 'No profiles yet.',
  'stars': 'Stars',
  'lettersDone': 'Lessons completed',
  'settings': 'Settings',
  'language': 'Language',
  'arabic': 'العربية',
  'english': 'English',
  'sessionLimit': 'Session length (minutes)',
  'unlockAll': 'Unlock all lessons',
  'unlockAllHint': 'For parents or testing',
  'openChildMode': 'Child mode',
  'gateTitle': 'Grown-ups only',
  'gateHold': 'Press and hold the button',
  'gateHoldButton': 'Hold',
  'gateSolve': 'Solve to continue',
  'gateWrong': 'Not quite, try again',
  'back': 'Back',
  'timeUpTitle': 'Time to rest',
  'timeUpBody': 'Play time is over. A grown-up can continue.',
  'continue': 'Continue',
  'loadError': "Couldn't load the lessons",
  'retry': 'Try again',
  'hi': 'Hi',
  'certificate': 'Certificate',
  'certAwardedTo': 'Awarded to',
  'certFinished': 'for finishing',
  'hooray': 'Hooray!',
  // --- first-launch onboarding (parent area, English) ---
  'obContinue': 'Continue',
  'obBack': 'Back',
  'obWelcomeTitle': 'Welcome to Dandoona English!',
  'obWelcomeBody': "We'll set up the right path for your child in two minutes.",
  'obNoAccount': 'Start without an account',
  'obNoAccountSub': 'Everything stays on this device',
  'obAccount': 'Create account / Log in',
  'obAccountSub': 'Sync across devices and back up progress',
  'obSignupTitle': 'Create your account',
  'obLoginTitle': 'Log in',
  'obEmail': 'Email',
  'obPassword': 'Password',
  'obFirstName': 'First name (optional)',
  'obGuardian': "I am the child's parent or guardian and I'm 18 or older",
  'obAgreePre': 'I agree to the ',
  'obPrivacy': 'Privacy Policy',
  'obAnd': ' and ',
  'obTerms': 'Terms',
  'obCreate': 'Create account',
  'obLogin': 'Log in',
  'obHaveAccount': 'I already have an account',
  'obNoAccountYet': "I don't have an account",
  'obNameTitle': "What's your child's name?",
  'obNameHint': 'A nickname is enough, no full name needed',
  'obNameLabel': 'Nickname',
  'obAvatarTitle': 'Pick a picture',
  'obAgeTitle': 'When was your child born?',
  'obMonth': 'Month',
  'obYear': 'Year',
  'obTrackFor': 'Best track:',
  'obTrackLL': 'Little Learners (ages 3–5)',
  'obMonth1': 'January',
  'obMonth2': 'February',
  'obMonth3': 'March',
  'obMonth4': 'April',
  'obMonth5': 'May',
  'obMonth6': 'June',
  'obMonth7': 'July',
  'obMonth8': 'August',
  'obMonth9': 'September',
  'obMonth10': 'October',
  'obMonth11': 'November',
  'obMonth12': 'December',
  'obLevelTitle': 'How much English does your child know?',
  'obLevel0': "Doesn't know any English yet",
  'obLevel1': 'Knows some letters',
  'obLevel2': 'Knows all letters',
  'obLevel3': 'Reads simple words',
  'obGoalTitle': 'How many minutes a day?',
  'obGoalHint': 'A little every day beats a lot once in a while',
  'obGoal5': '5 minutes',
  'obGoal10': '10 minutes',
  'obGoal15': '15 minutes',
  'obGoal5Sub': 'A light start',
  'obGoal10Sub': 'Best for most children',
  'obGoal15Sub': 'For keen learners',
  'obRemindTitle': 'Shall we remind you every day?',
  'obRemindBody': 'A reminder on this phone only, no outside service',
  'obTimeMorning': 'Morning 8:00',
  'obTimeAfternoon': 'Afternoon 4:00',
  'obTimeEvening': 'Evening 7:00',
  'obRemindMe': 'Remind me',
  'obRemindLater': 'Remind me later',
  'obNoReminder': 'No reminder',
  'obPathReady': "{name}'s path is ready!",
  'obRowTrack': 'Track',
  'obRowStart': 'Starting point',
  'obRowGoal': 'Daily goal',
  'obRowReminder': 'Reminder',
  'obStartLearning': 'Start learning',
  'obGreetIam': "I'm Dandoona!",
  'obGreetLets': "Let's learn English together!",
  'obLetsGo': "Let's go!",
  'whoIsPlaying': 'Who is playing?',
  'wardrobeHint': 'Collect stars to unlock new accessories',
  'thisWeek': 'This week',
  'syncTitle': 'Account & sync',
  'deleteAccount': 'Delete account & data',
  'deleteAccountTitle': 'Delete the account permanently?',
  'deleteAccountBody': 'Your account, children and progress will be erased from the server for good. Data on this device stays.',
  'accountDeleted': 'Account deleted',
  'syncOptional': 'Optional: the app works fully offline.',
  'serverUrl': 'Server address',
  'email': 'Email',
  'password': 'Password',
  'login': 'Sign in',
  'register': 'Create account',
  'signOut': 'Sign out',
  'syncNow': 'Sync now',
  'signedInAs': 'Signed in as',
  'lastSync': 'Last sync',
  'signedInOk': 'Signed in',
  'syncDone': 'Synced',
  'syncNetwork': 'Could not reach the server',
  'syncAuth': 'Wrong email or password',
  'syncInvalid': 'Please check the details',
  'syncFailed': 'Sync failed, try again later',
  'activities': 'Activities',
  'minutes': 'Minutes',
  'activeDays': 'Active days',
  'd0': 'Mon',
  'd1': 'Tue',
  'd2': 'Wed',
  'd3': 'Thu',
  'd4': 'Fri',
  'd5': 'Sat',
  'd6': 'Sun',
};
