import 'package:flutter/widgets.dart';

/// Hand-written localisation (no code generation). The parent area uses the language chosen in settings
/// (Arabic by default, RTL); the child area always uses English. A test keeps both maps in sync.
class Strings {
  const Strings._(this._m, this.locale);

  final Map<String, String> _m;
  final Locale locale;

  static const ar = Strings._(_arabic, Locale('ar'));
  static const en = Strings._(_english, Locale('en'));

  static Strings forCode(String code) => code == 'en' ? en : ar;

  bool get isRtl => locale.languageCode == 'ar';
  TextDirection get direction => isRtl ? TextDirection.rtl : TextDirection.ltr;

  /// `s('save')`. A missing key is a bug caught by the parity test; at runtime the key itself is shown.
  String call(String key) => _m[key] ?? key;

  static Iterable<String> get arabicKeys => _arabic.keys;
  static Iterable<String> get englishKeys => _english.keys;
}

const Map<String, String> _arabic = {
  'appName': 'دندونة إنجليش',
  'welcomeTitle': 'أهلاً بك!',
  'welcomeBody': 'لنُنشئ ملفًا لطفلك ليبدأ تعلّم الإنجليزية بالأصوات والصور والمرح.',
  'start': 'ابدأ',
  'childProfiles': 'ملفات الأطفال',
  'addChild': 'إضافة طفل',
  'editChild': 'تعديل الملف',
  'childName': 'اسم الطفل (اسم مستعار)',
  'nameHint': 'من فضلك لا تُدخل الاسم الكامل',
  'birthYear': 'سنة الميلاد',
  'chooseAvatar': 'اختر صورة',
  'save': 'حفظ',
  'cancel': 'إلغاء',
  'delete': 'حذف',
  'deleteChildTitle': 'حذف الملف؟',
  'deleteChildBody': 'سيتم حذف الملف وتقدّم الطفل من هذا الجهاز، ومن حسابك على الخادم أيضًا إن كانت المزامنة مفعّلة.',
  'pendingDeletes': 'عمليات حذف بانتظار الاتصال بالخادم:',
  'errName': 'أدخل اسمًا من حرف إلى 30 حرفًا',
  'errBirthYear': 'سنة الميلاد غير مناسبة (العمر من 2 إلى 13 سنة)',
  'parentArea': 'منطقة الأهل',
  'dashboard': 'لوحة التقدّم',
  'noChildren': 'لا توجد ملفات بعد.',
  'stars': 'النجوم',
  'lettersDone': 'الحروف المكتملة',
  'settings': 'الإعدادات',
  'language': 'اللغة',
  'arabic': 'العربية',
  'english': 'English',
  'sessionLimit': 'مدة الجلسة بالدقائق',
  'unlockAll': 'فتح جميع الحروف',
  'unlockAllHint': 'للأهل أو للتجربة',
  'openChildMode': 'وضع الطفل',
  'gateTitle': 'للكبار فقط',
  'gateHold': 'اضغط مطوّلًا على الزر',
  'gateHoldButton': 'اضغط مطوّلًا',
  'gateSolve': 'احسب الناتج للمتابعة',
  'gateWrong': 'إجابة غير صحيحة، حاول مرة أخرى',
  'back': 'رجوع',
  'timeUpTitle': 'حان وقت الاستراحة',
  'timeUpBody': 'انتهى وقت اللعب. يمكن للكبار المتابعة.',
  'continue': 'متابعة',
  'loadError': 'تعذّر تحميل الدروس',
  'retry': 'إعادة المحاولة',
  'hi': 'أهلاً',
  'certificate': 'شهادة',
  'whoIsPlaying': 'من سيلعب؟',
  'wardrobeHint': 'اجمع النجوم لفتح إكسسوارات جديدة',
  'thisWeek': 'هذا الأسبوع',
  'syncTitle': 'الحساب والمزامنة',
  'deleteAccount': 'حذف الحساب وبياناته',
  'deleteAccountTitle': 'حذف الحساب نهائيًا؟',
  'deleteAccountBody': 'سيتم حذف حسابك وجميع الأطفال والتقدّم من الخادم نهائيًا. تبقى البيانات على هذا الجهاز.',
  'accountDeleted': 'تم حذف الحساب',
  'syncOptional': 'اختياري: التطبيق يعمل كاملاً بدون إنترنت.',
  'serverUrl': 'عنوان الخادم',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'login': 'تسجيل الدخول',
  'register': 'إنشاء حساب',
  'signOut': 'تسجيل الخروج',
  'syncNow': 'مزامنة الآن',
  'signedInAs': 'مسجّل الدخول:',
  'lastSync': 'آخر مزامنة',
  'signedInOk': 'تم تسجيل الدخول',
  'syncDone': 'تمت المزامنة',
  'syncNetwork': 'تعذّر الاتصال بالخادم',
  'syncAuth': 'البريد أو كلمة المرور غير صحيحة',
  'syncInvalid': 'تحقق من البيانات المدخلة',
  'syncFailed': 'فشلت المزامنة، حاول لاحقًا',
  'activities': 'الأنشطة',
  'minutes': 'الدقائق',
  'activeDays': 'أيام النشاط',
  'd0': 'إث',
  'd1': 'ثل',
  'd2': 'أر',
  'd3': 'خم',
  'd4': 'جم',
  'd5': 'سب',
  'd6': 'أح',
};

const Map<String, String> _english = {
  'appName': 'Dandoona English',
  'welcomeTitle': 'Welcome!',
  'welcomeBody': "Let's create a profile for your child to start learning English with sounds, pictures and fun.",
  'start': 'Start',
  'childProfiles': 'Child profiles',
  'addChild': 'Add child',
  'editChild': 'Edit profile',
  'childName': "Child's nickname",
  'nameHint': "Please don't enter a full name",
  'birthYear': 'Birth year',
  'chooseAvatar': 'Choose an avatar',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'deleteChildTitle': 'Delete this profile?',
  'deleteChildBody': "The profile and progress will be removed from this device, and from your synced account on the server if sync is on.",
  'pendingDeletes': 'Deletions waiting to reach the server:',
  'errName': 'Enter a name (1-30 characters)',
  'errBirthYear': 'Birth year must give an age of 2 to 13',
  'parentArea': 'Parent area',
  'dashboard': 'Progress dashboard',
  'noChildren': 'No profiles yet.',
  'stars': 'Stars',
  'lettersDone': 'Letters completed',
  'settings': 'Settings',
  'language': 'Language',
  'arabic': 'العربية',
  'english': 'English',
  'sessionLimit': 'Session length (minutes)',
  'unlockAll': 'Unlock all letters',
  'unlockAllHint': 'For parents or testing',
  'openChildMode': 'Child mode',
  'gateTitle': 'Grown-ups only',
  'gateHold': 'Press and hold the button',
  'gateHoldButton': 'Hold',
  'gateSolve': 'Solve to continue',
  'gateWrong': 'Not quite, try again',
  'back': 'Back',
  'timeUpTitle': 'Time to rest',
  'timeUpBody': 'Play time is over. A grown-up can continue.',
  'continue': 'Continue',
  'loadError': "Couldn't load the lessons",
  'retry': 'Try again',
  'hi': 'Hi',
  'certificate': 'Certificate',
  'whoIsPlaying': 'Who is playing?',
  'wardrobeHint': 'Collect stars to unlock new accessories',
  'thisWeek': 'This week',
  'syncTitle': 'Account & sync',
  'deleteAccount': 'Delete account & data',
  'deleteAccountTitle': 'Delete the account permanently?',
  'deleteAccountBody': 'Your account, children and progress will be erased from the server for good. Data on this device stays.',
  'accountDeleted': 'Account deleted',
  'syncOptional': 'Optional: the app works fully offline.',
  'serverUrl': 'Server address',
  'email': 'Email',
  'password': 'Password',
  'login': 'Sign in',
  'register': 'Create account',
  'signOut': 'Sign out',
  'syncNow': 'Sync now',
  'signedInAs': 'Signed in as',
  'lastSync': 'Last sync',
  'signedInOk': 'Signed in',
  'syncDone': 'Synced',
  'syncNetwork': 'Could not reach the server',
  'syncAuth': 'Wrong email or password',
  'syncInvalid': 'Please check the details',
  'syncFailed': 'Sync failed, try again later',
  'activities': 'Activities',
  'minutes': 'Minutes',
  'activeDays': 'Active days',
  'd0': 'Mon',
  'd1': 'Tue',
  'd2': 'Wed',
  'd3': 'Thu',
  'd4': 'Fri',
  'd5': 'Sat',
  'd6': 'Sun',
};
