using System.Text;
using AssetGenerator.Curriculum;

namespace AssetGenerator;

/// <summary>`decisions`: regenerates docs/asset-decisions.md (every image's source, pick and reason; phonemes to listen to; spend).</summary>
public static class DecisionsDoc
{
    public static string Build(Layout layout, IReadOnlyList<Lesson> lessons)
    {
        var picks = Picks.Load(layout);
        var ledger = new CostLedger(layout.LedgerPath, 25m);
        var voiceFiles = lessons.SelectMany(l => LessonPlan.Audio(l).Select(a => (l, a))).ToList();
        var images = lessons.SelectMany(l => LessonPlan.Images(l).Select(i => (l, i))).ToList();
        var sb = new StringBuilder();

        sb.AppendLine("# Asset decisions");
        sb.AppendLine();
        sb.AppendLine("Generated by `tools/AssetGenerator -- decisions` from the curriculum, `content/generated/picks.json` and the cost ledger.");
        sb.AppendLine("To swap a pick: `approve --lesson <id> --word <key> --variant <n> --reason \"...\"` (or draw a new SVG in `content/art/`), then re-run `decisions` and `export`.");
        sb.AppendLine();
        sb.AppendLine($"- Images: **{images.Count}** total, **{images.Count(i => i.i.IsSvg)} self-drawn** (SVG, never sent to OpenAI), **{images.Count(i => !i.i.IsSvg)} OpenAI**.");
        sb.AppendLine($"- Rule: self-drawn when a simple flat drawing is clear to a 3-year-old; OpenAI only for animals, detailed objects/food and the mascot. All images follow `content/style/art-style.md` and `content/style/palette.json`.");
        sb.AppendLine();

        sb.AppendLine("## Mascot");
        var mascot = picks.FirstOrDefault(p => p.Lesson == "mascot");
        sb.AppendLine(mascot is null
            ? "Not locked yet (`mascot --approve N --reason \"...\"`)."
            : $"- **{mascot.Source}**, {mascot.Variant}, locked as `content/style/mascot.reference.webp`. Why: {mascot.Reason}");
        sb.AppendLine();
        sb.AppendLine("Replaced mascot (2026-10-07): the generated otter (OpenAI concept v1, brown otter with a teal bandana). Its assets were:");
        sb.AppendLine("- `content/style/mascot.reference.webp` (replaced by Dandoona), `mobile/kids_english_app/assets/images/mascot/mascot.webp` (re-exported from the new reference);");
        sb.AppendLine("- `content/generated/mascot/_review/mascot.v1..v4.webp` (concept sheets, deleted);");
        sb.AppendLine("- the 5 accessory SVGs in `content/art/accessories/` were drawn for the otter's proportions and brown outline, so they were redrawn for Dandoona (night-ink outline, positions fitted to her head and chest).");
        sb.AppendLine("No lesson illustration contains the otter (no word uses `mascot: true`), so none had to be regenerated.");
        sb.AppendLine();

        var reused = lessons.SelectMany(l => LessonPlan.Reused(l).Select(r => (l, r))).ToList();
        if (reused.Count > 0)
        {
            sb.AppendLine("## Reused pictures");
            sb.AppendLine($"{reused.Count} pictures of the Colors unit are copied from the Letters unit (same file, nothing new generated). OpenAI is not used for any Colors picture: every new object, swatch and drawing to color in is self-drawn SVG in palette.json colors.");
            sb.AppendLine();
            sb.AppendLine("| Lesson | Word | Copied from |");
            sb.AppendLine("|---|---|---|");
            foreach (var (l, r) in reused) sb.AppendLine($"| {l.Id} | {r.Key} | {r.Reuse} |");
            sb.AppendLine();
        }

        sb.AppendLine("## Images");
        sb.AppendLine("| Lesson | Word | Source | Pick | Why |");
        sb.AppendLine("|---|---|---|---|---|");
        foreach (var (l, i) in images)
        {
            if (i.IsSvg)
                sb.AppendLine($"| {l.Id} | {i.Key} | **self-drawn** | `content/art/{l.Track}/{l.Id}/{i.Key}.svg` | Simple flat shape, clear at a glance; drawn in SVG with the shared palette. |");
            else
            {
                var p = picks.FirstOrDefault(x => x.Lesson == l.Id && x.Key == i.Key);
                sb.AppendLine(p is null
                    ? $"| {l.Id} | {i.Key} | **OpenAI** | _not approved yet_ | |"
                    : $"| {l.Id} | {i.Key} | **OpenAI** | {p.Variant} | {p.Reason.Replace("|", "/")} |");
            }
        }
        sb.AppendLine();

        sb.AppendLine("## Needs human listening");
        sb.AppendLine("Text-to-speech is unreliable for isolated sounds. Listen to these and, if wrong, record your own as `phoneme.override.mp3` next to the generated file (export always prefers your recording).");
        sb.AppendLine();
        sb.AppendLine("Phoneme clips:");
        foreach (var (l, a) in voiceFiles.Where(v => v.a.IsPhoneme))
            sb.AppendLine($"- [{(File.Exists(layout.AudioOverride(l, "phoneme")) ? "x" : " ")}] **{l.Letter}** `{l.Phoneme}` - `content/generated/{l.Track}/{l.Id}/audio/phoneme.gen.mp3`{(File.Exists(layout.AudioOverride(l, "phoneme")) ? " (your recording in place)" : "")}");
        sb.AppendLine();
        sb.AppendLine("Letter intros are built from parts joined with pauses (spoken name, 0.7 s, the letter's sound, 0.5 s, the sound again, 0.7 s, the example word).");
        sb.AppendLine("The sound clips are chosen and scored by `tools/verify-audio` (method and score per letter in `content/generated/phoneme-choices.json`; review page `content/generated/verify-audio.html`).");
        foreach (var (l, a) in voiceFiles.Where(v => v.a.Role == "intro"))
            sb.AppendLine(a.ComposeWord is null ? $"- {l.Id}: \"{a.Text}\"" : $"- {l.Id}: \"{a.Text}\" + /{l.Phoneme?.Trim('/')}/ x2 + `{a.ComposeWord}`");
        sb.AppendLine();

        sb.AppendLine("## Spend");
        sb.AppendLine($"Total: **${ledger.Total:0.00}** (limit $25.00). " + string.Join(", ", ledger.Entries.GroupBy(e => e.Service).Select(g => $"{g.Key} ${g.Sum(e => e.Usd):0.00}")) + ".");
        if (ledger.Entries.Any(e => e.Estimated)) sb.AppendLine("Some entries are estimates (no usage figure was returned).");
        return sb.ToString();
    }

    public static string Write(Layout layout, IReadOnlyList<Lesson> lessons)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(layout.DecisionsDoc)!);
        File.WriteAllText(layout.DecisionsDoc, Build(layout, lessons), new UTF8Encoding(false));
        return layout.DecisionsDoc;
    }
}
